# Generated by Django 6.0.5 on 2026-06-06 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="章節名稱")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "章節",
                "verbose_name_plural": "章節",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(verbose_name="題目內容")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "簡單"), ("medium", "中等"), ("hard", "困難")],
                        default="medium",
                        max_length=10,
                        verbose_name="難度",
                    ),
                ),
                ("is_original", models.BooleanField(default=False, verbose_name="原創題")),
                ("explanation", models.TextField(blank=True, verbose_name="解析")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz.chapter",
                        verbose_name="章節",
                    ),
                ),
            ],
            options={
                "verbose_name": "題目",
                "verbose_name_plural": "題目",
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.CharField(max_length=500, verbose_name="選項內容")),
                ("is_correct", models.BooleanField(default=False, verbose_name="是否正確")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="quiz.question",
                        verbose_name="題目",
                    ),
                ),
            ],
            options={
                "verbose_name": "選項",
                "verbose_name_plural": "選項",
            },
        ),
        migrations.CreateModel(
            name="UserAnswerHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_correct", models.BooleanField(verbose_name="是否答對")),
                ("wrong_count", models.PositiveIntegerField(default=0, verbose_name="答錯次數")),
                ("answered_at", models.DateTimeField(auto_now=True)),
                ("next_review", models.DateTimeField(blank=True, null=True, verbose_name="下次複習時間")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.question",
                        verbose_name="題目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "作答紀錄",
                "verbose_name_plural": "作答紀錄",
                "unique_together": {("user", "question")},
            },
        ),
    ]
